### ISSUE TITLE
Http request error 505 when the first line of the request is fragmented.

### ISSUE THREAD

**Issue by kindablissy** [uNetworking/uWebSockets#1776] opened 2024-08-21 06:41 UTC
If the first line of http request somehow misses to go in the same packet as `` [method] [path] [version]\r\n`` but instead gets something like ``[method]`` and `` [path] [version]\r\n `` it will return with version not supported error. Is this expected ?

**Comment by uNetworkingAB** [comment] 2024-08-21 09:20
Must be a regression from when more detailed errors were added because this is not the old behavior

**Comment by slavslavov** [comment] 2024-08-28 10:45
I am also seeing this error when trying to serve a Qt application built for Webassembly. I am attaching the files which are served if this will help for debugging. If I serve the files locally, all works. But my real setup is on a remote server with HAProxy terminating the TLS certificate and then forwarding to uWebsockets server. Webassembly application will require these two headers to be set

```
                res->writeHeader("Cross-Origin-Embedder-Policy", "require-corp");
                res->writeHeader("Cross-Origin-Opener-Policy", "same-origin");
```
[gallery.zip](https://github.com/user-attachments/files/16782197/gallery.zip)

**Comment by uNetworkingAB** [comment] 2024-08-28 11:37
There is no debugging needed it happens here https://github.com/uNetworking/uWebSockets/blob/9cca5d68e0ac7153d8250445c076a9ffc3d58dae/src/HttpParser.h#L370

It needs to check whether it reached end of data and if so, just return 0 instead of setting error. Then it will keep accepting more data instead of immediately closing with error.

**Comment by uNetworkingAB** [comment] 2024-08-31 18:43
Needs a good test that just takes a simple request, chunks it up into every combination of two segements and asserts same outcome for all. Working on it

**Comment by uNetworkingAB** [comment] 2024-09-01 17:02
You mind testing latest commit? It still lacks a test but should probably work now

**Comment by slavslavov** [comment] 2024-09-01 19:32
I tested with commit 6b966b24ee2d186fcfd86c3f3d450fa913782c60 and I can't see the error any more. I used the same environment as before - HAProxy terminating TLS and forwarding to uWebsockets with checks and Proxy Protocol V2. I ran  tcpdump and wireshark for about 20 minutes, also quite intensively requesting a large .wasm file. All looks good now.

**Comment by uNetworkingAB** [comment] 2024-09-01 19:34
Great I just need a unit test for this and will release

**Closed** 2024-10-08 15:06 UTC
Labels: bug, has fix, regression
