### ISSUE TITLE
memset ws->getUserData() pointer causes segmentation fault in open handler.

### ISSUE THREAD

**Issue by f-cg** [uNetworking/uWebSockets#863] opened 2019-03-25 16:22 UTC
```
#include "App.h"
#include <cstdlib>

int main() {
    /* ws->getUserData returns one of these */
    struct PerSocketData {
        int a[32];
    };  

    /* Very simple WebSocket echo server */
    uWS::App().ws<PerSocketData>("/*", {
        /* Settings */
        .compression = uWS::SHARED_COMPRESSOR,
        .maxPayloadLength = 16 * 1024,
        /* Handlers */
        .open = [](auto *ws, auto *req) {
                auto psd=(PerSocketData*)ws->getUserData();
                std::memset(psd,0,sizeof(PerSocketData));
        },  
        .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
            ws->send(message, opCode);
        },  
    }).listen(9001, [](auto *token) {
        if (token) {
            std::cout << "Listening on port " << 9001 << std::endl;
        }
    }).run();
}
```

**Comment by alexhultman** [comment] 2019-03-25 16:49
#859

**Comment by tommitytom** [comment] 2019-03-27 07:44
I'm having this issue too, on Windows using libuv.  I think it's because of this:
```c
// this one is broken, see us_poll
struct us_poll *us_poll_resize(struct us_poll *p, struct us_loop *loop, unsigned int ext_size) {

    // do not support it yet
    return p;

    struct us_poll *new_p = realloc(p, sizeof(struct us_poll) + ext_size);
    if (p != new_p) {
        new_p->uv_p.data = new_p;
    }

    return new_p;
}
```

**Comment by alexhultman** [comment] 2019-03-28 18:01
@f-cg I can reproduce this. That's really bad.

**Comment by alexhultman** [comment] 2019-03-28 18:01
@tommitytom It reproduces on epoll-only, so there's no libuv-related issue as far I know

**Comment by alexhultman** [comment] 2019-04-03 21:22
Alright I found the issue. It's a pretty big bug - Http parser does not properly stop after upgrading to websocket and this works fine in most cases but if you change websocket user data you modify parts of the former http socket and it blows up.

**Comment by alexhultman** [comment] 2019-04-03 22:22
Should be fixed now

**Closed by alexhultman** 2019-04-03 22:23 UTC
Labels: bug, high priority

**Comment by jvo203** [comment] 2019-10-15 08:30
Hi Alex, this issue does not seem to be fixed yet. Would you please re-open it. Am having the same problem in C++ with the latest v0.16.0:
```
struct UserData {
  std::string session_id;
  std::string datasetid;
  std::vector<std::string> all_ids;
};

.ws<UserData>("/websocket/*", {
(...)
.open = [](auto *ws, auto *req) { 
(...)
struct UserData* user = (struct UserData*) ws->getUserData();                        

                        if(user != NULL)
                        {
                          std::cout << "non-NULL user data" << std::endl;
                          user->session_id = std::string("NULL");
                        }
```
Modifying supposedly non-NULL user data in the .open handler results in a segmentation fault. This is a serious show-stopper, otherwise the upgrade from v0.14 has been going fine.

**Comment by alexhultman** [comment] 2019-10-15 10:08
https://github.com/uNetworking/uWebSockets/issues/896

**Comment by jvo203** [comment] 2019-10-15 11:20
Thank you. I get it. Will implement new/delete upon .open/.close with struct UserData holding just a pointer to the proper user data structure.
