### ISSUE TITLE
the app crash when using the version 0.14.8

### ISSUE THREAD

**Issue by AVFoundation** [uNetworking/uWebSockets#903] opened 2019-06-03 07:46 UTC
Hello, I have a crash when using version 0.14.8. Do anybody can help me?

the crash info:
 **0xf623a1d7 void uS::Socket::startTimeout<&uWS::WebSocket<false>::onEnd>(int)::{lambda(uS::Timer*)#1}::operator()(uS::Timer*) const +0x24** 

Here is my code.

void WSClient::initHub() {
    m_hub.reset();
    m_hub = std::make_shared<uWS::Hub>();
    m_hub->onPong(
        [this](uWS::WebSocket<uWS::CLIENT> *ws, char * message, size_t length) {
            //
        }
        );

    m_hub->onConnection(
        [this](uWS::WebSocket<uWS::CLIENT> * ws, uWS::HttpRequest req) {
            m_ws = ws;
           //
        }
        );

    m_hub->onMessage(
        [this](uWS::WebSocket<uWS::CLIENT> *ws, char * message, size_t length, uWS::OpCode opCode) {
            //
        }
        );
    m_hub->onDisconnection(   
        [this](uWS::WebSocket<uWS::CLIENT> * ws, int code, char * message, size_t length) {
            m_ws = nullptr;
            //
        }
        );
}
void WSClient::disconnect() {
    if (m_ws) {
        m_ws->close();
        m_ws = nullptr;
    }
}
bool WSClient::init() {
    initHub();
    m_wsThread = std::thread(&WSClient::start, this);
    return true;
}

void WSClient::start() {
    while (!m_stopFlag) {
            m_hub->run();
           //initHub();
        }
    }
}

**Comment by alexhultman** [comment] 2019-06-05 00:52
This seems like ill-use. You cannot mix threads like that.

**Comment by AVFoundation** [comment] 2019-06-05 06:57
Can you give me a example? I just want to start a websocket client when the client is disconnect.

**Comment by alexhultman** [comment] 2019-06-08 00:22
You have to use only one thread per hub, cannot mix threads. Closing as not a bug

**Closed by alexhultman** 2019-06-08 00:22 UTC
